# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf1129869313bc271649162a7171b2d87a251253d64efb39e96eed1049866d9dada906db99332b74a8321bfe729149504744539c99f4d0d36aed62950a86bd8a

test:
  secret_key_base: 55bd897b80a8616ebab3342957a9e2896ff43ea89e35a10960068327d88f98eb731e188c56bc327e516b0ed2a213ac3974b87481df559faf189261d16671b52f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
